project:
  type: book
  output-dir: docs

book:
  title: "Recipes from our catalogue"
  author: "Grants"
  date: "2024-07-29"
  chapters:
    - index.qmd
    - breakfast.qmd
    - appetizers.qmd
    - dinner.qmd
    - bread.qmd
    - desert.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

